import { test, expect } from '@playwright/test';

test('release tasks are collapsed and all four evidence actions work', async ({page})=>{
  const base={product_id:'nested',version:1,created:1,updated:1,status:'delivered'};
  const product={...base,id:'nested',name:'交付任务项目',status:'active'};
  const batch={...base,id:'batch',title:'release-20261009',branch:'release-20261009',day:'20261009',status:'collecting',run_ids:['task']};
  const task={run:{...base,id:'task',title:'修复行情空白'},requirement:{id:'requirement',title:'行情缺陷',evidence:'巡检发现行情区域空白'},signals:[],inspections:[{...base,id:'inspection',title:'行情页面巡检'}],evidence:[],prs:[{label:'代码评审 MR',pr_url:'https://github.com/example/repo/pull/12'},{label:'上线 PR',pr_url:'https://github.com/example/repo/pull/13'}]};
  await page.route('**/api/products',r=>r.fulfill({json:[product]}));
  await page.route('**/api/deliveries',r=>r.fulfill({json:[batch]}));
  await page.route('**/api/products/nested/workbench',r=>r.fulfill({json:{sessions:[],reviews:[],events:[]}}));
  await page.route('**/api/products/nested/delivery-board',r=>r.fulfill({json:{prs:[],release_prs:[{id:'release-pr',delivery_id:'batch',pr_url:'https://github.com/example/repo/pull/13',number:13,title:'release-20261009',git_status:'open',status:'approved',updated:1}],issues:[]}}));
  await page.route('**/api/deliveries/batch/tasks',r=>r.fulfill({json:{tasks:[task],day:'20261009',missing_ids:[]}}));
  await page.route('**/api/runs/task/usage',r=>r.fulfill({json:{tokens:1234,sources:[{id:'trace',action:'develop',tokens:1234,collected:true,budget_kind:'tokens'}],day:'2026-10-09',project_tokens_used:3456,project_tokens_limit:10000,receipts:[{action:'develop',at:1,result:{status:'pass',summary:'行情渲染已验证'}}],evidence:[],reviews:[]}}));
  await page.goto('/autopilot?project=nested');
  await page.getByRole('button',{name:'待合并 1',exact:true}).click();
  const drawer=page.locator('.ant-drawer-content');
  await expect(drawer.getByRole('button',{name:'展开问题'})).toHaveAttribute('aria-expanded','false');
  await expect(drawer.getByText('修复行情空白',{exact:true})).toHaveCount(0);
  await drawer.getByRole('button',{name:'展开问题'}).click();
  await expect(drawer.getByText('修复行情空白',{exact:true})).toBeVisible();
  await expect(drawer.getByRole('button',{name:'PR 详情',exact:true})).toBeInViewport();
  await page.screenshot({path:'.playwright/delivery-tasks-expanded.png'});
  const modal=page.locator('.ant-modal-content');
  await drawer.getByRole('button',{name:'任务详情',exact:true}).click();
  await expect(modal.getByText('行情缺陷',{exact:true})).toBeVisible();
  await modal.getByRole('button',{name:'Close',exact:true}).click();
  await drawer.getByRole('button',{name:'发现过程（巡检记录）',exact:true}).click();
  await expect(modal.getByText('行情页面巡检',{exact:true}).first()).toBeVisible();
  await modal.getByRole('button',{name:'Close',exact:true}).click();
  await drawer.getByRole('button',{name:'PR 详情',exact:true}).click();
  await expect(modal.getByRole('link',{name:'https://github.com/example/repo/pull/12'})).toHaveAttribute('href','https://github.com/example/repo/pull/12');
  await modal.getByRole('button',{name:'Close',exact:true}).click();
  await drawer.getByRole('button',{name:'查看用量',exact:true}).click();
  await expect(modal.getByText('1,234 Token',{exact:true})).toBeVisible();
  await expect(modal.getByText('3,456 / 10,000 Token',{exact:true})).toBeVisible();
  await modal.getByRole('tab',{name:'过程数据',exact:true}).click();
  await expect(modal.getByText('行情渲染已验证',{exact:true}).first()).toBeVisible();
  await modal.getByRole('button',{name:'Close',exact:true}).click();
  await drawer.getByRole('button',{name:'收起问题'}).click();
  await expect(drawer.getByText('修复行情空白',{exact:true})).not.toBeVisible();
});
